/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import Controller.Disco;
import Controller.TreeController;
import Model.Folder;
import Model.MyFile;
import java.util.ArrayList;
import javax.swing.tree.MutableTreeNode;



/**
 *
 * @author Natalia 
 */
public class FileSystem_Window extends javax.swing.JFrame {

    /**
     * Creates new form FileSystem_Window
     */
    private DefaultTreeModel model;
    private DefaultMutableTreeNode selectedNode;
    private Disco discController;
    private TreeController treeController;
    //Auxliars nodes for copy a node inside to other node
    private DefaultMutableTreeNode originNode=null;
    private DefaultMutableTreeNode destinationNode=null;
    
    public FileSystem_Window() {
        initComponents();
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
        //////////////////////////////////////////////////////////////
        Folder root = new Folder("root",true,"[Root]");
        treeController = new TreeController(root);
        treeController.addFolder(root);
        //private TreeController treeController = new TreeController();
        //////////////////////////////////////////////////////////////

        Folder myfolder = new Folder("Folder name", true, "Root");
        Folder myfolder2 = new Folder("Folder2 name", true, "Root");
        Folder myfolder3 = new Folder("Folder3 name", true, "Root");

        
        ArrayList<Integer> array = new  ArrayList<Integer>(); 
        MyFile file1 = new MyFile("File1.txt", "Root/Folder name", array,  "HASDFASDsdfasfdas12341234", 12);
        MyFile file2 = new MyFile("File2.txt", "Root/Folder name", array,  "saveevqfqasdfasdd", 12);
        MyFile file3 = new MyFile("File3.txt", "Root/Folder name", array,  "asdffsdfsdtrhhtht", 12);
        MyFile file4 = new MyFile("File4.txt", "Root/Folder name", array,  "asdasdsdffsdfdssdffds", 12);
        
        myfolder.addFiles(file1);
        myfolder.addFiles(file2);
        myfolder.addFiles(file3);
        myfolder.addFiles(file4);
        
        myfolder2.addFiles(file1);
        myfolder2.addFiles(file2);
        myfolder2.addFiles(file3);
        myfolder2.addFiles(file4);
        
        myfolder3.addFiles(file1);
        myfolder3.addFiles(file2);
        myfolder3.addFiles(file3);
        myfolder3.addFiles(file4);
                
        treeController.setRoot(myfolder);
        treeController.addFolder(myfolder2);
        treeController.addFolder(myfolder3);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumberOfSectors = new javax.swing.JTextField();
        txtSectorSize = new javax.swing.JTextField();
        btnDisk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblFileName = new javax.swing.JLabel();
        txtFileExtension = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextContents = new javax.swing.JTextArea();
        btnCreateFile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblCurrentDir = new javax.swing.JLabel();
        txtCurrentDir = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtFolderName = new javax.swing.JTextField();
        btnAddFolder = new javax.swing.JButton();
        lblAdd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCurrentDir2 = new javax.swing.JLabel();
        txtCurrentDir2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        btnSaveChanges = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblExtention = new javax.swing.JLabel();
        lblCreation = new javax.swing.JLabel();
        lblModification = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblContents = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPathCopy = new javax.swing.JTextField();
        jTextFieldDestinationPath = new javax.swing.JTextField();
        jButtonCopy = new javax.swing.JButton();
        jButtonCopyGetDestination = new javax.swing.JButton();
        jButtonCopyGetOrigin1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("dummy");
        treeNode1.add(treeNode2);
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        jLabel1.setText("Number of sector");

        jLabel2.setText("Sector's size");

        btnDisk.setText("Prepare disk");
        btnDisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisk)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnumberOfSectors)
                            .addComponent(txtSectorSize, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnumberOfSectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSectorSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnDisk)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CREATE", jPanel3);

        lblFileName.setText("File name:");

        jTextContents.setColumns(20);
        jTextContents.setRows(5);
        jScrollPane3.setViewportView(jTextContents);

        btnCreateFile.setText("Create File");
        btnCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFileActionPerformed(evt);
            }
        });

        jLabel5.setText("Contents:");

        jLabel6.setText("Extension:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtFileExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(181, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateFile)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lblFileName)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(250, Short.MAX_VALUE)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblFileName)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFileExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnCreateFile)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("FILE", jPanel2);

        lblCurrentDir.setText("Current directory");

        txtCurrentDir.setEnabled(false);
        txtCurrentDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentDirActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAddFolder.setText("Add folder");
        btnAddFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFolderActionPerformed(evt);
            }
        });

        lblAdd.setText("Folder's name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrentDir)
                            .addComponent(lblAdd))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddFolder))
                            .addComponent(txtCurrentDir, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentDir)
                    .addComponent(txtCurrentDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFolder)
                    .addComponent(lblAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("MKDIR", jPanel1);

        lblCurrentDir2.setText("Current file: ");

        txtCurrentDir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentDir2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Text:");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        btnSaveChanges.setText("Save changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblCurrentDir2))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveChanges)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(txtCurrentDir2))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentDir2)
                    .addComponent(txtCurrentDir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSaveChanges)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODFILE", jPanel4);

        jLabel7.setText("Name:");

        jLabel8.setText("Extension:");

        jLabel9.setText("Modification date:");

        jLabel10.setText("Creation date:");

        jLabel11.setText("Size:");

        jLabel12.setText("Contents:");

        lblName.setText("jLabel12");

        lblExtention.setText("jLabel12");

        lblCreation.setText("jLabel12");

        lblModification.setText("jLabel12");

        lblSize.setText("jLabel12");

        lblContents.setText("jLabel12");

        jButton1.setText("Consult");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblExtention)
                            .addComponent(lblCreation)
                            .addComponent(lblModification)
                            .addComponent(lblSize)
                            .addComponent(lblContents)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblName))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblExtention))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCreation))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblModification))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblSize))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblContents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("PROPERTIES", jPanel5);

        jLabel13.setText("Find:");

        jTextField2.setText("jTextField2");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jButton2.setText("Accept");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton2)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("FIND", jPanel6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MOVE", jPanel8);

        jLabel3.setText("Path to Copy:");

        jLabel14.setText("Destination Path");

        jTextFieldPathCopy.setEditable(false);
        jTextFieldPathCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPathCopyActionPerformed(evt);
            }
        });

        jTextFieldDestinationPath.setEditable(false);
        jTextFieldDestinationPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinationPathActionPerformed(evt);
            }
        });

        jButtonCopy.setText("Copy");
        jButtonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyActionPerformed(evt);
            }
        });

        jButtonCopyGetDestination.setText("GetNode");
        jButtonCopyGetDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyGetDestinationActionPerformed(evt);
            }
        });

        jButtonCopyGetOrigin1.setText("GetNode");
        jButtonCopyGetOrigin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyGetOrigin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCopy)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPathCopy)
                    .addComponent(jTextFieldDestinationPath, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCopyGetDestination)
                    .addComponent(jButtonCopyGetOrigin1))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPathCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCopyGetOrigin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDestinationPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCopyGetDestination))
                .addGap(18, 18, 18)
                .addComponent(jButtonCopy)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COPY", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPane1))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();

        int cont = selectedNode.getChildCount();
        DefaultMutableTreeNode child = new DefaultMutableTreeNode();
        for (int i=0; i<cont; i++){
            child = (DefaultMutableTreeNode) selectedNode.getChildAt(i);
            //System.out.println(child);
        }
        
        txtCurrentDir.setText(jTree.getSelectionPath().toString());
        txtCurrentDir2.setText(jTree.getSelectionPath().toString());
    }//GEN-LAST:event_jTreeValueChanged

    private void btnCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFileActionPerformed
        String filename =txtFileName.getText()+"."+txtFileExtension.getText(); 
        //System.out.println(filename);
        createNode(filename);  
        
    }//GEN-LAST:event_btnCreateFileActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deteleNode();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFolderActionPerformed
        String filename = txtFolderName.getText(); 
        DefaultMutableTreeNode newFile = createNode(filename);
        DefaultMutableTreeNode n = (DefaultMutableTreeNode)selectedNode.getLastLeaf();
        String rute = treeController.createRute(jTree.getSelectionPath().toString(), filename);
        Folder newFolder = new Folder(filename, false, rute);
        MyFile dummy =  new MyFile("dummy", "[Root, dummy]");
        //System.out.println("The rute is: "+rute);
        treeController.addFolder(newFolder);
        //System.out.println(treeController.toString());
        //System.out.println(treeController.searchFile("[Root, dummy]"));
        //System.out.println(newFolder);
        
        
        
        //treeController.searchFile(String path)
       
    }//GEN-LAST:event_btnAddFolderActionPerformed

    private void txtCurrentDir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentDir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentDir2ActionPerformed

    private void txtCurrentDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentDirActionPerformed

    private void btnDiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiskActionPerformed
        String sectors =txtnumberOfSectors.getText();
        String sector_size = txtSectorSize.getText();
        Disco.inicializarDisco(Integer.parseInt(sectors),Integer.parseInt(sector_size));
        Disco.createTxtFile();
        Disco.writeFromJson();
    }//GEN-LAST:event_btnDiskActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        //System.out.println( jTree.getSelectionPath().toString());
        lblName.setText("asdfasd");
        lblExtention.setText("asdfasd");
        lblCreation.setText("asdfasd");
        lblModification.setText("asdfasd");
        lblSize.setText("asdfasd");
        lblContents.setText("asdfasd");

        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextFieldPathCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPathCopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPathCopyActionPerformed

    private void jTextFieldDestinationPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinationPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinationPathActionPerformed

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode aux = null;
        
        if (destinationNode!=null && originNode!=null && destinationNode.getAllowsChildren()){         
            DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
            
            System.out.println("Origen: "+originNode.toString());
            System.out.println("Destino: "+destinationNode.toString());
            
            for (int i=0;i<jTree.getModel().getChildCount(destinationNode);i++){
                aux = (DefaultMutableTreeNode) jTree.getModel().getChild(destinationNode, i);
                
                if (aux.toString().equals(originNode.toString())){
                    int resp = JOptionPane.showConfirmDialog(null, "Do you want overwrite the file/dir?", "YES_NO_OPTION", 
                                                            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    switch (resp) {
                        case 0://yes
                            destinationNode.remove(i); break;
                        case 1: 
                            originNode=null; destinationNode=null; return;
                    }
                }
            }
            model.insertNodeInto(originNode, destinationNode, destinationNode.getChildCount());
        }
        //make these auxiliars nodes to null.
        originNode=null;
        destinationNode=null; 
        
    }//GEN-LAST:event_jButtonCopyActionPerformed

    private void jButtonCopyGetDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyGetDestinationActionPerformed
        
        if (selectedNode!=null && selectedNode!=jTree.getModel().getRoot()){
            destinationNode = selectedNode;
            jTextFieldDestinationPath.setText(jTree.getSelectionPath().toString());
            
        }else{
            destinationNode=null;
        }
    }//GEN-LAST:event_jButtonCopyGetDestinationActionPerformed

    
    private DefaultMutableTreeNode copyNode(DefaultMutableTreeNode node){
        DefaultMutableTreeNode aux = null;
        DefaultMutableTreeNode child = null;
        
        if(node.isLeaf()){
            aux=(DefaultMutableTreeNode) node.clone();
        }else{
            aux = (DefaultMutableTreeNode) node.clone();
            for (int i=0;i<jTree.getModel().getChildCount(node);i++){
                //get the each child from the node that we will copy.
                child = (DefaultMutableTreeNode) jTree.getModel().getChild(node, i);
                //make a copy of that child                
                child = copyNode(child);              
                aux.add(child);
            }
        }
        
        return aux;
        
    }
    
    private void jButtonCopyGetOrigin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyGetOrigin1ActionPerformed

        if (selectedNode!=null && selectedNode!=jTree.getModel().getRoot()){
            originNode = (DefaultMutableTreeNode) selectedNode.clone();
            DefaultMutableTreeNode aux;
            
            for (int i=0;i<jTree.getModel().getChildCount(selectedNode);i++){
                aux= (DefaultMutableTreeNode) jTree.getModel().getChild(selectedNode, i);
                originNode.insert(copyNode(aux),originNode.getChildCount());
            }      
            jTextFieldPathCopy.setText(jTree.getSelectionPath().toString());
  
        }else{
            destinationNode=null;
        }
    }//GEN-LAST:event_jButtonCopyGetOrigin1ActionPerformed

    private boolean isPossibleCreate(String filename){
       
        int cont = selectedNode.getChildCount();
        DefaultMutableTreeNode child = new DefaultMutableTreeNode();
        for (int i=0; i<cont; i++){
            child = (DefaultMutableTreeNode) selectedNode.getChildAt(i);
            if (child.toString().equals(filename)){
                int resp = JOptionPane.showConfirmDialog(null, "Do you want overwrite the file?",
                "YES_NO_OPTION", JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
                switch (resp) {
                case 0: //Yes
                    //Aqui eliminar el archivo o dir 
                    return true; //Hay otro y se se quiere sobrescribir 
                case 1: //No
                    return false; //Hay otro y no se quiere sobrescribir 
                } 
            }
        }
        return true; //No hay otro y se puede agregar 
    }
    
    private DefaultMutableTreeNode createNode(String filename){
        
        DefaultMutableTreeNode newFile = null;
        if (isPossibleCreate(filename)){
            newFile = new DefaultMutableTreeNode(filename);
            if (selectedNode!=null){
                //System.out.println(selectedNode);
                DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
                model.insertNodeInto(newFile, selectedNode, selectedNode.getChildCount());
            }
        }
        return newFile;
    }
    private void deteleNode(){
        
        if (selectedNode!=null && selectedNode!=jTree.getModel().getRoot()){
            DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
            model.removeNodeFromParent(selectedNode);
            model.reload();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileSystem_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileSystem_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileSystem_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileSystem_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileSystem_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFolder;
    private javax.swing.JButton btnCreateFile;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisk;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCopy;
    private javax.swing.JButton jButtonCopyGetDestination;
    private javax.swing.JButton jButtonCopyGetOrigin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextContents;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldDestinationPath;
    private javax.swing.JTextField jTextFieldPathCopy;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblContents;
    private javax.swing.JLabel lblCreation;
    private javax.swing.JLabel lblCurrentDir;
    private javax.swing.JLabel lblCurrentDir2;
    private javax.swing.JLabel lblExtention;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblModification;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSize;
    private javax.swing.JTextField txtCurrentDir;
    private javax.swing.JTextField txtCurrentDir2;
    private javax.swing.JTextField txtFileExtension;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtFolderName;
    private javax.swing.JTextField txtSectorSize;
    private javax.swing.JTextField txtnumberOfSectors;
    // End of variables declaration//GEN-END:variables
}
